# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160101_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_sync',
            field=models.DateField(blank=True, null=True, verbose_name='last sync'),
        ),
    ]
