# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('monthly_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='monthly limit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='word')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='reporting.Category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('account_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='account number')),
                ('bank_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='bank code')),
                ('identification', models.CharField(blank=True, max_length=255, null=True, verbose_name='identification')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'bank transfer'), (2, 'card'), (3, 'installment'), (4, 'cash'), (5, 'other')], default=5, verbose_name='kind')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='account name')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='bank name')),
                ('currency', models.PositiveSmallIntegerField(choices=[(1, 'CZK'), (2, 'EUR')], verbose_name='currency')),
                ('recipient_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='recipient message')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reporting.Category', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
